- hosts: k8s_masters
  become: yes
  gather_facts: false
  tasks:
    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command as fact
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Reset worker node
  import_playbook: reset_worker_node.yaml

- hosts: k8s_workers
  become: yes
  tasks:
    - name: Join cluster
      shell: "{{ hostvars[groups['k8s_masters'][0]].join_command }}"
      args:
        chdir: $HOME
        creates: node_joined.txt
