- name: Reset master node
  hosts: k8s_masters
  become: yes
  tasks:
    - name: Reset master node
      shell: sudo kubeadm reset --force
      become: yes

    - name: Remove master config
      shell: rm -rf $HOME/.kube/config
      become: yes

- name: Initialize cluster
  import_playbook: initialize_cluster.yaml
